version: '3.8'

services:
  # =============================================================================
  # DATABASE SERVICE - PostgreSQL
  # =============================================================================
  db:
    image: postgres:16.2-alpine
    container_name: mtmx-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=mtmxdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mtmxdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mtmx-network

  # =============================================================================
  # BACKEND SERVICE - Spring Boot
  # =============================================================================
  backend:
    container_name: mtmx-backend
    build:
      context: ./mt-mx-be
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mtmxdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - WEB_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000,http://localhost:5173
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_COM_MTMX=INFO
      - LOGGING_LEVEL_ROOT=WARN
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - SPRINGDOC_API_DOCS_PATH=/v3/api-docs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - mtmx-network

  # =============================================================================
  # FRONTEND SERVICE - React/Vite (Production)
  # =============================================================================
  frontend:
    container_name: mtmx-frontend
    build:
      context: ./mt-mx-fe
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mtmx-network

  # =============================================================================
  # DEVELOPMENT SERVICES (Optional - use with --profile dev)
  # =============================================================================
  
  # Frontend Development Service
  frontend-dev:
    container_name: mtmx-frontend-dev
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./mt-mx-fe:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      backend:
        condition: service_healthy
    profiles:
      - dev
    networks:
      - mtmx-network

  # Backend Development Service
  backend-dev:
    container_name: mtmx-backend-dev
    image: openjdk:21-jdk-slim
    working_dir: /app
    ports:
      - "8082:8081"
    volumes:
      - ./mt-mx-be:/app
      - maven_cache:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mtmxdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - WEB_CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=dev
      - LOGGING_LEVEL_COM_MTMX=DEBUG
      - LOGGING_LEVEL_ROOT=INFO
    command: sh -c "apt-get update && apt-get install -y maven wget && mvn clean compile && mvn spring-boot:run"
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - dev
    networks:
      - mtmx-network

  # =============================================================================
  # MONITORING & UTILITIES (Optional)
  # =============================================================================
  
  # pgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: mtmx-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mtmx.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles:
      - tools
    networks:
      - mtmx-network

volumes:
  postgres_data:
    driver: local
  maven_cache:
    driver: local

networks:
  mtmx-network:
    driver: bridge
    name: mtmx-network 