server:
  port: 8081

spring:
  application:
    name: mt-mx-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mtmxdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSSSS

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    probes:
      enabled: true

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true

# Logging configuration
logging:
  level:
    com.mtmx: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS configuration
web:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/mtmxdb

logging:
  level:
    com.mtmx: INFO
    root: WARN

web:
  cors:
    allowed-origins: "http://localhost:3000,http://frontend:3000"

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.mtmx: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

web:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173"

---
# H2 in-memory database profile
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:mtmxdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.mtmx: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

web:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173" 